version: "3.7"
services:
  file-indexer-frontend-dev:
    image: node:13.13.0-alpine3.11
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command: sh -c "cd /home/node/app && npm install && npm run dev"
    ports:
      - 8080:8080
